### PR TITLE
Add the lab new command

### PR DESCRIPTION
**Pull request by toniecrumley**
This command will create a new project based on the project template.

*** Be sure to delete test repos from Github after testing.  ***

Instructions for installation and usage can be found in the README.
https://github.com/lasseignelab/lab-framework/tree/lab-new

Once installation is successful, run the following commands to test this branch:
```
cd ~/bin/lab-framework
git checkout lab-new
```
Once the branch is checked out, go to your user data directory and test the `lab new` command based on the README linked above.  I have started using my name for my test repo name.  If we all do that we won't all be trying to create a repo named `test`.

To uninstall for retest, run the following command:
```
rm -rf ~/bin/lab-framework
```
Then delete the following line from `~/.bash_profile`:
```
export PATH="$PATH:$HOME/bin/lab-framework"
```

### CODE REVIEW

**Comment by toniecrumley** [comment]
@emmafjones @tchowton Since GITHUB_ACCOUNT was unclear to both of you, it clearly needs improvement. It seems that GITHUB_OWNER would be more consistent with the create repo page and the `lab new` help. Would that be clearer to you?

**Comment by tchowton** [comment]
> @emmafjones @tchowton Since GITHUB_ACCOUNT was unclear to both of you, it clearly needs improvement. It seems that GITHUB_OWNER would be more consistent with the create repo page and the `lab new` help. Would that be clearer to you?

I think that is more clear

**Review by emmafjones — APPROVED** [review]
This now works for me

**Review by lizzyjoan — APPROVED** [review]
looks good and works for me!

**Review by tchowton — APPROVED** [review]

**Review by tchowton — DISMISSED** [review]
I tested the lab new -o and lab new --skip-git. Both worked

**Pull request merged**
