### PR TITLE
Lab md5 --slurm option

### PR DESCRIPTION
**Pull request by toniecrumley**
Add `--slurm` option to the `md5` command.  When the files are very large the command can take a long time and it can overload login server nodes.  The `--slurm` option will use Slurm to run the command on large files.  If the value of the option is `run` then it will use `srun` and the output will be shown in the current terminal window.  If the value of the option is `batch` then it will use `sbatch` and the output will be directed to a file named lab-md5-<job_id>.out in the current directory.

To prepare for testing, perform these commands in a terminal.
```
cd ~/bin/lab-framework
git pull
git checkout -b lab-md5-slurm origin/lab-md5-slurm
lab help md5
```
This should change the `lab` CLI to use this version of the `md5` command in the pull request.  The `--slurm` option should show in the help.

When you are through testing, change back to the released version with the following commands.
```
cd ~/bin/lab-framework
git checkout main
```

Examples from lab-framework directory calculating the md5sum for all files in the commands directory:
```
lab md5 commands
lab md5 --slurm run commands
lab md5 -s batch commands
```

### CODE REVIEW

**Review by lizzyjoan — DISMISSED** [review]
looks good and new slurm options worked just fine for me

**Comment by tchowton** [comment]
@toniecrumley Do you think we should have a flag for specifying an output directory?

**Comment by tchowton** [comment]
@toniecrumley is there a way we could give it 2 directories and it would compare everything in there and tell us what is different?

**Comment by toniecrumley** [comment]
> @toniecrumley Do you think we should have a flag for specifying an output directory?

@tchowton Yes, I will add that.  Thanks!

**Comment by toniecrumley** [comment]
> @toniecrumley is there a way we could give it 2 directories and it would compare everything in there and tell us what is different?

I believe that is a different command.  This one seems like it will still be useful for getting md5sums for a group of large files to verify that they downloaded properly since it can run in a Slurm job.  

Also, the author could do output a `lab md5` file of their data to include with the project.  Then the reviewer could run the command against the data they downloaded and make sure everything matches.  There could be a command for this like `lab verify`.   I added a card for this.  https://www.wrike.com/open.htm?id=1494153912

I added a `lab md5diff DIR1 DIR2` and `lab md5diff FILE1 FILE2' card to the wrike board.  It will use `lab md5` to do the work and then provide a diff of the results.  https://www.wrike.com/open.htm?id=1494153623

**Comment by toniecrumley** [comment]
> @toniecrumley is there a way we could give it 2 directories and it would compare everything in there and tell us what is different?

In the meantime, the `diff` command can be used after generating two files with the `lab md5` command.

```
[acrumley@login004 acrumley]$ cat -n lab-md5-11111.out
     1
     2	Files included:
     3	3edbdbe249e7cd7dcbd972fe6aad8a62  ./bin/docker/rstudio-prefs.json
     4	8727a3b060e4c558308055ff9f056466  ./bin/README
     5	0f7179a1e37c249cb0bc93c38d879ab1  ./data/README
     6	8ca543915f71163395f20d7317532a52  ./doc/README
     7	43bd364a97a38fb1da7c57e6381886c1  ./LICENSE
     8	f330b29f4a0af8cc33eee17341065092  ./README.md
     9	d9cf640595e45433ce64d30a82a1ec91  ./README.Rmd
    10	44d9d88ec061c83bd1605fc85b5abf36  ./results/README
    11	b26c809519d8f39ae594efc3d8e86c49  ./src/README
    12
    13	Combined MD5 checksum:
    14	8ac1c7541ef58465bc941b8387f38514
    15
[acrumley@login004 acrumley]$ cat -n lab-md5-22222.out
     1
     2	Files included:
     3	4bcad117e5f6a0a626153ba75bd40c04  ./bin/docker/Dockerfile
     4	3edbdbe249e7cd7dcbd972fe6aad8a62  ./bin/docker/rstudio-prefs.json
     5	8727a3b060e4c558308055ff9f056466  ./bin/README
     6	1f7179a1e37c249cb0bc93c38d879ab1  ./data/README
     7	8ca543915f71163395f20d7317532a52  ./doc/README
     8	43bd364a97a38fb1da7c57e6381886c1  ./LICENSE
     9	f330b29f4a0af8cc33eee17341065092  ./README.md
    10	d9cf640595e45433ce64d30a82a1ec91  ./README.Rmd
    11	44d9d88ec061c83bd1605fc85b5abf36  ./results/README
    12	b26c809519d8f39ae594efc3d8e86c49  ./src/README
    13
    14	Combined MD5 checksum:
    15	7ac1c7541ef58465bc941b8387f38514
    16
[acrumley@login004 acrumley]$ diff -U 0 lab-md5-11111.out lab-md5-22222.out
--- lab-md5-11111.out	2024-09-14 10:22:01.731412000 -0500
+++ lab-md5-22222.out	2024-09-14 10:30:24.996530000 -0500
@@ -2,0 +3 @@
+4bcad117e5f6a0a626153ba75bd40c04  ./bin/docker/Dockerfile
@@ -5 +6 @@
-0f7179a1e37c249cb0bc93c38d879ab1  ./data/README
+1f7179a1e37c249cb0bc93c38d879ab1  ./data/README
@@ -14 +15 @@
-8ac1c7541ef58465bc941b8387f38514
+7ac1c7541ef58465bc941b8387f38514
```

**Comment by toniecrumley** [comment]
@tchowton An option for specifying the file output has been added.  cc @emmafjones @adc0032 @lizzyjoan

**Review by tchowton — APPROVED** [review]
The output option is a great add. Everything worked.

**Pull request merged**
